spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cineapp_db
    username: everton
    password: rocha123
    show-sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true

  main:
    banner-mode: console
  banner:
    location: classpath:banner.txt
    charset: UTF8
  output:
    ansi:
      enabled: always